# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Gradle

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        #cache: maven
    - name: Build with Gradle
      run: |
        chmod +x gradlew
        ./gradlew shadowJar --no-daemon
        mkdir staging/ && cp dev.skidfuscator.client.standalone/build/libs/client-standalone-all.jar staging
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Skidfuscator.jar
        path: dev.skidfuscator.client.standalone/build/libs/client-standalone-all.jar
        if-no-files-found: warn
